### ISSUE TITLE
Static files handled by web server

### ISSUE THREAD

**Issue by askvortsov1** [FriendsOfFlarum/clockwork#5]
When installing this, the web server needs to be configured such that clockwork's js/css/images aren't handled by the filesystem. Perhaps:

- Sample web server config could be provided or
- `index.html` could be processed to strip out .js/.css/.png line endings, and those could be re-added in the assets controller

**Comment by datitisev** [comment]
What web server configuration affects it? Is it the Flarum provided one? That'd make sense, as I don't use it locally. But this extension shouldn't be used in production anyway.

**Comment by askvortsov1** [comment]
Yep! Confirmed for nginx for me (I hacked my local install with the 2nd option on the list above to get it to work)

**Comment by luceos** [comment]
Did #7 fully fix this? @askvortsov1

**Comment by askvortsov1** [comment]
Yeah, adding the config to nginx fixed it for me :+1:
